name: brew test-bot
on:
  push:
    branches: main
  pull_request:
jobs:
  test-bot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # https://docs.brew.sh/Support-Tiers
          # https://github.com/actions/runner-images
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
          - macos-14
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems
      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - name: Build formulae
        run: |
          set +e
          brew test-bot --only-formulae 2>&1 | tee test-bot.log
          exit_code=$?
          if [ $exit_code -ne 0 ] || grep -q "^==> FAILED" test-bot.log; then
            echo "::error::brew test-bot failed"
            exit 1
          fi
        if: github.event_name == 'pull_request'
        shell: bash
